import {
  contributionSchema,
  createSchema,
  decisionSchema,
  goalPatchSchema,
  goalSchema,
  joinSchema,
  noteSchema,
  roleSchema,
  updateSchema,
  voteSchema,
} from "../../modules/circles/circles.service.js";
import { confirmationSchema, resolveSchema, statementSchema } from "../../modules/circles/mpesa.js";
import { arr, bool, dateTime, described, int, nullable, obj, oneOf, ref, str, url, uuid, type ErrorCase, type Op } from "../builder.js";
import { person } from "../schemas.js";

export const tag = {
  name: "Circles",
  description:
    "Founder circles. A money circle is a group of people who already know each other, saving towards shared goals; the only way in is an invite from its organiser. A learning circle has no money and may be found and joined.\n\n**FoundersLink keeps a circle's records. It never receives, holds or forwards money**: members pay into the circle's own account, and the organiser or treasurer records what was paid.\n\nPast joining, the caller must be a member of the circle; to anyone else it returns `404`.\n\n**M-Pesa.** The statement import and the Paybill confirmation endpoint have never been run against a real M-Pesa statement or Safaricom's Daraja sandbox. The column names and confirmation fields were written from memory of Safaricom's formats. Only the matching and reconciliation logic is tested.",
};

const NO_CIRCLE: ErrorCase = [404, "NOT_FOUND", "No such circle, or the caller is not a member."];
const ORGANISER: ErrorCase = [403, "FORBIDDEN", "The caller is not the circle's organiser."];
const KEEPER: ErrorCase = [403, "FORBIDDEN", "The caller is neither the organiser nor the treasurer."];
const NOT_MONEY: ErrorCase = [409, "NOT_A_MONEY_CIRCLE", "A learning circle has no contributions."];
const circleId = { id: described(uuid, "The circle id.") };
const UNTESTED = "**Not run against the real thing:** this has never been tried with a real M-Pesa statement or Safaricom's sandbox.";

const note = {
  id: uuid,
  circle_id: uuid,
  author_id: uuid,
  kind: described(oneOf(["note", "meeting"]), "`meeting` when `held_at` was given."),
  held_at: nullable(dateTime),
  body: str,
  created_at: dateTime,
};

export const ops: Op[] = [
  {
    method: "post",
    path: "/circles",
    summary: "Create a circle",
    description:
      "The creator becomes its organiser, and a group chat is created for it. Two rules are checked in code and are not in the schema below: a `money` circle cannot be `discoverable`, and a `learning` circle cannot have `contribution_amount_kes`.",
    access: "approved",
    body: createSchema,
    ok: { status: 201, description: "The circle.", schema: ref("Circle") },
  },
  {
    method: "get",
    path: "/circles",
    summary: "My circles",
    access: "approved",
    ok: {
      description: "Circles the caller belongs to, most recently joined first.",
      schema: arr(
        obj({
          id: uuid,
          name: str,
          type: oneOf(["money", "learning"]),
          my_role: oneOf(["organiser", "treasurer", "member"]),
          members: int,
          registration_status: oneOf(["unregistered", "in_progress", "registered"]),
        }),
      ),
    },
  },
  {
    method: "get",
    path: "/circles/suggested",
    summary: "Learning circles I could join",
    description: "Discoverable learning circles the caller is not in, those nearest her sector and county first. Money circles are never suggested to anyone.",
    access: "approved",
    ok: {
      description: "Suggestions.",
      schema: arr(
        obj({ id: uuid, name: str, description: nullable(str), sector: nullable(str), county: nullable(str), members: int, reasons: arr(str) }),
      ),
    },
  },
  {
    method: "get",
    path: "/circles/invites/:token",
    summary: "Preview an invite",
    description: "What someone holding an invite link sees before she joins.",
    access: "approved",
    params: { token: described(str, "The invite token.") },
    ok: {
      description: "The circle behind the invite.",
      schema: obj({ name: str, description: nullable(str), type: oneOf(["money", "learning"]), members: int }),
    },
    errors: [[404, "NOT_FOUND", "The invite is unknown, revoked, used up or expired."]],
  },
  {
    method: "post",
    path: "/circles/join",
    summary: "Join with an invite",
    access: "approved",
    body: joinSchema,
    ok: { description: "The circle, now joined.", schema: ref("Circle") },
    errors: [
      [404, "NOT_FOUND", "The invite is unknown, revoked, used up or expired."],
      [409, "ALREADY_A_MEMBER", "The caller is already in this circle."],
    ],
  },
  {
    method: "get",
    path: "/circles/:id",
    summary: "One circle",
    description: "Members and their roles, who has paid this week or month, and goals with progress. Only payments matched to a member are counted.",
    access: "approved",
    params: circleId,
    ok: { description: "The circle.", schema: ref("Circle") },
    errors: [NO_CIRCLE],
  },
  {
    method: "patch",
    path: "/circles/:id",
    summary: "Update a circle",
    description: "Organiser only. `paybill_number` is the circle's own Paybill or Till number, used to match Paybill confirmations to this circle.",
    access: "approved",
    params: circleId,
    body: updateSchema,
    ok: { description: "The circle.", schema: ref("Circle") },
    errors: [
      ORGANISER,
      NO_CIRCLE,
      [409, "NOT_A_MONEY_CIRCLE", "A contribution or a Paybill number was set on a learning circle."],
      [409, "PAYBILL_TAKEN", "Another circle already uses this Paybill or Till number."],
    ],
  },
  {
    method: "post",
    path: "/circles/:id/join",
    summary: "Join a learning circle",
    description: "Without an invite. Only a learning circle that chose to be discoverable.",
    access: "approved",
    params: circleId,
    ok: { description: "The circle, now joined.", schema: ref("Circle") },
    errors: [
      [404, "NOT_FOUND", "No such circle, or it is a money circle, or it is not discoverable."],
      [409, "ALREADY_A_MEMBER", "The caller is already in this circle."],
    ],
  },
  {
    method: "post",
    path: "/circles/:id/invites",
    summary: "Create an invite link",
    description: "Organiser only. Valid for 7 days. For a money circle each link lets in one person; a learning circle's link works for anyone until it expires.",
    access: "approved",
    params: circleId,
    ok: {
      status: 201,
      description: "The invite.",
      schema: obj({ token: str, path: described(str, "`/circles/join/<token>`, for the frontend to turn into a full link."), expires_at: dateTime, single_use: bool }),
    },
    errors: [ORGANISER, NO_CIRCLE],
  },
  {
    method: "delete",
    path: "/circles/:id/members/:userId",
    summary: "Remove a member, or leave",
    description: "The organiser removes someone, or a member removes herself. She also leaves the circle's group chat.",
    access: "approved",
    params: { ...circleId, userId: described(uuid, "The member to remove. The caller's own id to leave.") },
    ok: { description: "Removed.", schema: obj({ circle_id: uuid, removed: uuid }) },
    errors: [
      [403, "FORBIDDEN", "Removing someone else, and the caller is not the organiser."],
      [404, "NOT_FOUND", "No such circle for the caller, or the target is not a member."],
      [409, "ORGANISER_CANNOT_LEAVE", "The organiser cannot leave or be removed."],
    ],
  },
  {
    method: "patch",
    path: "/circles/:id/members/:userId",
    summary: "Change a member's role",
    description: "Organiser only. The organiser's own role cannot be changed.",
    access: "approved",
    params: { ...circleId, userId: described(uuid, "The member's user id.") },
    body: roleSchema,
    ok: { description: "The circle.", schema: ref("Circle") },
    errors: [ORGANISER, [404, "NOT_FOUND", "No such circle for the caller, or the target is not a member whose role can be changed."]],
  },
  {
    method: "post",
    path: "/circles/:id/goals",
    summary: "Add a goal",
    description: "Organiser only.",
    access: "approved",
    params: circleId,
    body: goalSchema,
    ok: { status: 201, description: "The goal.", schema: ref("CircleGoal") },
    errors: [ORGANISER, NO_CIRCLE],
  },
  {
    method: "patch",
    path: "/circles/:id/goals/:goalId",
    summary: "Edit a goal",
    description: "Organiser only.",
    access: "approved",
    params: { ...circleId, goalId: described(uuid, "The goal id.") },
    body: goalPatchSchema,
    ok: { description: "The goal.", schema: ref("CircleGoal") },
    errors: [ORGANISER, [404, "NOT_FOUND", "No such circle for the caller, or no such goal in it."]],
  },
  {
    method: "post",
    path: "/circles/:id/contributions",
    summary: "Record a contribution",
    description:
      "The organiser or treasurer writes down a payment a member made to the circle's own account. This is a record only: FoundersLink does not receive or move the money, and nothing checks that the payment happened. `mpesa_receipt` is uppercased before it is checked, so lowercase is accepted.",
    access: "approved",
    params: circleId,
    body: contributionSchema,
    ok: { status: 201, description: "The payment record.", schema: ref("PaymentRecord") },
    errors: [
      [400, "NOT_A_MEMBER", "`member_id` is not a member of this circle."],
      [400, "UNKNOWN_GOAL", "`goal_id` does not belong to this circle."],
      [400, "FUTURE_DATE", "`paid_at` is in the future."],
      KEEPER,
      NO_CIRCLE,
      NOT_MONEY,
      [409, "RECEIPT_ALREADY_RECORDED", "A payment with this M-Pesa receipt is already recorded for the circle."],
    ],
  },
  {
    method: "get",
    path: "/circles/:id/contributions",
    summary: "Contribution history",
    description: "Every matched payment, newest first: who paid, when, and who wrote it down. Unmatched payments are in the reconciliation.",
    access: "approved",
    params: circleId,
    ok: {
      description: "The history.",
      schema: arr(
        obj({
          id: uuid,
          member: nullable(person),
          amount_kes: int,
          paid_at: dateTime,
          goal: nullable(obj({ id: uuid, title: str })),
          mpesa_receipt: nullable(str),
          source: oneOf(["manual", "statement", "paybill_callback"]),
          matched_status: oneOf(["matched"]),
          note: nullable(str),
          recorded_by: uuid,
          recorded_at: dateTime,
        }),
      ),
    },
    errors: [NO_CIRCLE],
  },
  {
    method: "post",
    path: "/circles/:id/notes",
    summary: "Add a note or meeting minutes",
    description: "Any member. With `held_at` it is the minutes of a meeting.",
    access: "approved",
    params: circleId,
    body: noteSchema,
    ok: { status: 201, description: "The note.", schema: obj(note) },
    errors: [NO_CIRCLE],
  },
  {
    method: "get",
    path: "/circles/:id/notes",
    summary: "Notes and minutes",
    access: "approved",
    params: circleId,
    ok: { description: "Newest first.", schema: arr(obj({ ...note, author: person })) },
    errors: [NO_CIRCLE],
  },
  {
    method: "post",
    path: "/circles/:id/decisions",
    summary: "Put a question to a vote",
    description: "Any member.",
    access: "approved",
    params: circleId,
    body: decisionSchema,
    ok: { status: 201, description: "The decision, open for votes.", schema: obj({ id: uuid, question: str, status: oneOf(["open"]) }) },
    errors: [NO_CIRCLE],
  },
  {
    method: "get",
    path: "/circles/:id/decisions",
    summary: "Decisions and their votes",
    access: "approved",
    params: circleId,
    ok: { description: "Newest first.", schema: arr(ref("CircleDecision")) },
    errors: [NO_CIRCLE],
  },
  {
    method: "post",
    path: "/circles/:id/decisions/:decisionId/vote",
    summary: "Vote on a decision",
    description: "One vote each. It can be changed while the decision is open.",
    access: "approved",
    params: { ...circleId, decisionId: described(uuid, "The decision id.") },
    body: voteSchema,
    ok: { description: "The decision with the new tally.", schema: ref("CircleDecision") },
    errors: [
      [404, "NOT_FOUND", "No such circle for the caller, or no such decision in it."],
      [409, "DECISION_CLOSED", "Voting has closed."],
    ],
  },
  {
    method: "post",
    path: "/circles/:id/decisions/:decisionId/close",
    summary: "Close a decision",
    description: "Organiser only.",
    access: "approved",
    params: { ...circleId, decisionId: described(uuid, "The decision id.") },
    ok: { description: "The closed decision.", schema: ref("CircleDecision") },
    errors: [ORGANISER, [404, "NOT_FOUND", "No such circle for the caller, or no open decision with this id."]],
  },
  {
    method: "post",
    path: "/circles/:id/statements",
    summary: "Import an M-Pesa statement",
    description: `Organiser or treasurer. Reads payments in from the rows of a statement, matches each to a member, and returns a summary. Send exactly one of \`rows\` or \`csv\`; that rule is checked in code and is not in the schema below. The upload itself is not stored. This request may be up to 1 MB, where others are limited to 100 kB.\n\n${UNTESTED} A real M-Pesa statement is a password-protected PDF, which this does not read: it takes rows or CSV text.\n\nA row is \`{ receipt, completed_at, details, paid_in_kes }\`. CSV needs a header line with columns for the receipt number, completion time, details and amount paid in. A payment is matched by a member's verified phone number appearing in \`details\` (whole, or masked in the middle), otherwise by every word of her name. If two members could fit, it is left unmatched. Rows with nothing paid in, repeated receipts and invalid rows are counted and skipped.`,
    access: "approved",
    params: circleId,
    body: statementSchema,
    ok: {
      description: "What was read.",
      schema: obj({
        rows: int,
        imported: int,
        matched: int,
        unmatched: int,
        duplicates: int,
        not_payments_in: int,
        errors: arr(obj({ row: described(int, "Counted from 1, not including the CSV header."), message: str })),
      }),
    },
    errors: [[400, "UNKNOWN_COLUMNS", "The CSV header lacks one of the needed columns."], KEEPER, NO_CIRCLE, NOT_MONEY],
  },
  {
    method: "get",
    path: "/circles/:id/reconciliation",
    summary: "Who has paid this period",
    description: "For the current week or month: who has paid, who still owes, and payments nobody has been matched to. Any member can read it; the details of unmatched payments go to the organiser and treasurer only.",
    access: "approved",
    params: circleId,
    ok: {
      description: "The reconciliation.",
      schema: obj({
        circle_id: uuid,
        period: described(
          nullable(obj({ starts: dateTime, frequency: oneOf(["weekly", "monthly"]), expected_per_member_kes: nullable(int) })),
          "Null when the circle has no contribution frequency. Then every matched payment counts.",
        ),
        collected_kes: int,
        members: arr(obj({ user_id: uuid, full_name: str, paid_kes: int, due_kes: int })),
        missing: arr(obj({ user_id: uuid, full_name: str, paid_kes: int, due_kes: int })),
        by_source: obj({ manual: int, statement: int, paybill_callback: int }),
        unmatched_count: int,
        unmatched: described(
          arr(
            obj({
              id: uuid,
              amount_kes: int,
              paid_at: dateTime,
              mpesa_receipt: nullable(str),
              payer_label: described(nullable(str), "What identified the payer, with most of any phone number masked."),
              source: str,
            }),
          ),
          "Empty for an ordinary member.",
        ),
      }),
    },
    errors: [NO_CIRCLE, NOT_MONEY],
  },
  {
    method: "patch",
    path: "/circles/:id/payments/:paymentId",
    summary: "Resolve an unmatched payment",
    description: "Organiser or treasurer. `{ member_id }` assigns the payment to a member; `{ ignore: true }` sets it aside as not a contribution. Send exactly one; that rule is checked in code and is not in the schema below.",
    access: "approved",
    params: { ...circleId, paymentId: described(uuid, "The payment record id.") },
    body: resolveSchema,
    ok: {
      description: "The payment after the change.",
      schema: obj({ id: uuid, matched_status: oneOf(["matched", "ignored"]), member_id: nullable(uuid) }),
    },
    errors: [
      [400, "NOT_A_MEMBER", "`member_id` is not a member of this circle."],
      KEEPER,
      [404, "NOT_FOUND", "No such circle for the caller, or no unmatched payment with this id."],
      NOT_MONEY,
    ],
  },
  {
    method: "post",
    path: "/payments/mpesa/callback/:secret",
    summary: "M-Pesa Paybill confirmation (called by Safaricom)",
    description: `Meant to be registered with Safaricom as the C2B confirmation URL for a circle's own Paybill. It records a payment Safaricom says was made; FoundersLink is not in the path of the money.\n\n${UNTESTED} The field names follow Daraja's C2B confirmation as remembered, and no real confirmation has ever been received.\n\nThere is no bearer token: the only guard is the secret in the URL, compared with \`MPESA_CALLBACK_SECRET\`. Without that variable the endpoint answers \`404\`. The origin of the request is not otherwise checked.\n\nThe circle is found by \`BusinessShortCode\` matching its \`paybill_number\`, and the member by the phone number or name typed as \`BillRefNumber\`. A payment for an unknown short code, or a receipt already recorded, is accepted and ignored. \`TransTime\` is read as East Africa Time.`,
    access: "public",
    params: { secret: described(str, "Must equal `MPESA_CALLBACK_SECRET`.") },
    body: confirmationSchema,
    ok: {
      description: "Always the same answer once the body is valid, whether or not anything was recorded.",
      schema: obj({ ResultCode: { type: "integer", const: 0 }, ResultDesc: oneOf(["Accepted"]) }),
    },
    errors: [[404, "NOT_FOUND", "The secret is wrong, or `MPESA_CALLBACK_SECRET` is not set."]],
  },
];
